site_name: UNYKAD
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
copyright: An idiot admires complexity, a genius admires simplicity. - Terry Davis
extra:
  generator: false
  social:
    - icon: fontawesome/brands/instagram
#      link: https://instagram.com/Unykad
    - icon: fontawesome/brands/tiktok
#      link: https://tiktok.com/Unykad
    - icon: fontawesome/brands/x-twitter
#      link: https://x.com/Unykad
theme:
  name: material
  favicon: assets/u1icofullSize.svg
  logo: assets/u1w.svg
  features:
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - header.autohide
  - announce.dismiss
  - navigation.indexes
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: purple
      scheme: default
      toggle: 
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - awesome-pages